### ISSUE TITLE
Template webapp UI elements

### ISSUE THREAD

**Issue by sixseconds** [sixseconds/BCIT_nb_iot#12]

**Comment by glowinginthedark** [comment]
We need template charts for:
- temperature
- humidity
- pressure
- magnetic field
- lux

We also need: 
- a component hierarchy 
- a decision on what kind of chart we will use for each type of reading
- what we will need to do about discrepancies between collected data (missing or additional fields)
- a decision on whether we can combine charts for multiple types of readings in one view
- a wireframe/rough structural template for how we will organize the user workflow (this is connected to the component hierarchy)
